### ISSUE TITLE
Having a demo of the retrieval tool

### ISSUE THREAD

**Issue by fedenanni** [ArchivesPortalEuropeFoundation/Topic-Detection#4]

**Comment by kerstarno** [comment]
@fedenanni Done. Fingers crossed that it'll work :-)

**Comment by fedenanni** [comment]
@kerstarno @stefanpapp-ape @martamu I am trying to set up a demo in Binder [here](https://mybinder.org/v2/gh/ArchivesPortalEuropeFoundation/Topic-Detection/a01ed376a6a0d2ac4ba231dcb06832bb1238b63d?filepath=InformationRetrieval.ipynb). It crashes at the moment, when downloading all the word embeddings, I am trying to find a work-around this issue.

**Comment by fedenanni** [comment]
@kerstarno @stefanpapp-ape @martamu ok, I tested Binder multiple times but it does not have enough memory to load the multilingual embeddings. I am testing now Google Colab. Otherwise I can make you a guide and you can install the code on your computer (I can guide you through it does not take much time) until we have a VM that we can use for the demo.

**Comment by kerstarno** [comment]
Hi @fedenanni - thanks for keeping us posted. Let's see how the test with Google Colab goes. Otherwise we could maybe use the call tomorrow for a run-through installing the code?

**Comment by fedenanni** [comment]
@kerstarno Good idea!
