### ISSUE TITLE
[BUG] Allow using different php actions depending on the interface

### ISSUE THREAD

**Issue by fedenanni** [ArchivesPortalEuropeFoundation/Topic-Detection#83]
Hi @kstamatis I am basically done with the very first prototype of the tagging interface. It runs in the `add-detector` branch and you might be able to test it already by cloning the repo and setting up the docker container. It should respond at:
`curl -v [specific ip]:5000/detect?lang=en&query=Barack+Obama+lives+in+Washington+with+his+family`

However I haven't tested it thoroughly yet with docker, so in case you get an error i'll fix it next week.

The only problem that I currently have when running it locally is that it seems that in your js script the .php file used seems to be hardcoded (see [here](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/blob/bff735786953e7c5c24669a72576515159adc37d/interface/js/script.js#L62)). However for the two interfaces i now need two different php actions:
- [index.html](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/blob/add-detector/interface/index.html) should point to [query.php](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/blob/add-detector/interface/query.php)
- [detect.html](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/blob/add-detector/interface/detect.html) should point to [detect.php](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/blob/add-detector/interface/detect.php)

I have expressed this in the htmls but I believe the js script overrides it. Would you mind helping me with this fix?
Otherwise no worries and I'll continue digging next week.

**Comment by kstamatis** [comment]
Hello Federico,
I think I have fixed the problem with this commit: https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/commit/2312575590cf7855ed00ff11aa25899227521f5b.
