### ISSUE TITLE
Change text from "alpha release" to "beta release"

### ISSUE THREAD

**Issue by kerstarno** [ArchivesPortalEuropeFoundation/Topic-Detection#93]
Hi @fedenanni, 

could we make sure that the text on the start page of the tool is updated to say "beta release", please? This would go for the development and the production version of the cross-lingual search tool (https://www.archivesportaleurope.net/topicdetection/ and https://test.archivesportaleurope.net/topicdetection/) as well as the new multilingual detection tool (https://test.archivesportaleurope.net/topicdetection/detect.html), when seeing the both as parts of one tool.

Thanks. :-)

**Comment by fedenanni** [comment]
@kerstarno no problem - I have updated it in the dev versions (commit [3506619](https://github.com/ArchivesPortalEuropeFoundation/Topic-Detection/commit/35066196ada7f1424dbdcf4df83da1225834dcf6) and the one right before), @kstamatis will be able to do the same in the production version by just pulling the `dev` branch (I don't have access to that server).

**Comment by kerstarno** [comment]
Hi @kstamatis - could you please make sure, this change is pulled through to the production version, so that it says "beta" release for the cross-lingual search under https://www.archivesportaleurope.net/topicdetection/ as well? Thanks!

**Comment by kstamatis** [comment]
Hi @kerstarno. Production has been updated along with this change as well.
